export const CONSTANTS = Object.freeze({
	// Transactions
	MAX_TRANSACTIONS_DISPLAYED: 4,

	// Pots
	MAX_POT_NAME_LENGTH: 50,
	MAX_POTS_DISPLAYED: 4,
	MIN_POTS: 0,

	// Budgets
	MAX_BUDGET_PERCENTAGE: 100,
	MIN_BUDGET_PERCENTAGE: 0,
	MIN_TARGET: 0,
	MAX_BUDGETS_DISPLAYED: 4,
	MIN_BUDGETS: 0,

	// Bills
	MAX_BILLS_DISPLAYED: 3,
	MIN_BILLS_DISPLAYED: 0,

	// Hours
	MORNING_START: 5,
	MORNING_END: 12,
	AFTERNOON_START: 12,
	AFTERNOON_END: 20,
	NIGHT_START: 20,
	NIGHT_END: 5,
});
