/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgres://username:password@database:5432/db123 -t bills -t budgets -t pgmigrations -t pots -t transactions -t users -s public
 *
 */


export type Json = unknown;

// Table bills
export interface Bills {
  id: number;
  name: string;
  amount: number;
  frequency: string | null;
  next_run: Date;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
}
export interface BillsInput {
  id?: number;
  name: string;
  amount: number;
  frequency?: string | null;
  next_run: Date;
  created_at?: Date;
  updated_at?: Date;
  deleted_at?: Date | null;
}
const bills = {
  tableName: 'bills',
  columns: ['id', 'name', 'amount', 'frequency', 'next_run', 'created_at', 'updated_at', 'deleted_at'],
  requiredForInsert: ['name', 'amount', 'next_run'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Bills,
  $input: null as unknown as BillsInput
} as const;

// Table budgets
export interface Budgets {
  id: number;
  name: string;
  theme: string;
  amount: number;
  maximum_spending: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
}
export interface BudgetsInput {
  id?: number;
  name: string;
  theme: string;
  amount: number;
  maximum_spending: number;
  created_at?: Date;
  updated_at?: Date;
  deleted_at?: Date | null;
}
const budgets = {
  tableName: 'budgets',
  columns: ['id', 'name', 'theme', 'amount', 'maximum_spending', 'created_at', 'updated_at', 'deleted_at'],
  requiredForInsert: ['name', 'theme', 'amount', 'maximum_spending'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Budgets,
  $input: null as unknown as BudgetsInput
} as const;

// Table pgmigrations
export interface Pgmigrations {
  id: number;
  name: string;
  run_on: Date;
}
export interface PgmigrationsInput {
  id?: number;
  name: string;
  run_on: Date;
}
const pgmigrations = {
  tableName: 'pgmigrations',
  columns: ['id', 'name', 'run_on'],
  requiredForInsert: ['name', 'run_on'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Pgmigrations,
  $input: null as unknown as PgmigrationsInput
} as const;

// Table pots
export interface Pots {
  id: number;
  name: string;
  theme: string;
  target: number;
  amount: number;
  total_saved: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
}
export interface PotsInput {
  id?: number;
  name: string;
  theme: string;
  target: number;
  amount?: number;
  total_saved?: number;
  created_at?: Date;
  updated_at?: Date;
  deleted_at?: Date | null;
}
const pots = {
  tableName: 'pots',
  columns: ['id', 'name', 'theme', 'target', 'amount', 'total_saved', 'created_at', 'updated_at', 'deleted_at'],
  requiredForInsert: ['name', 'theme', 'target'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Pots,
  $input: null as unknown as PotsInput
} as const;

// Table transactions
export interface Transactions {
  id: number;
  amount: number;
  category: string;
  transaction_type: string;
  sender: string;
  sender_picture: string | null;
  date: Date;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
}
export interface TransactionsInput {
  id?: number;
  amount: number;
  category: string;
  transaction_type: string;
  sender: string;
  sender_picture?: string | null;
  date: Date;
  created_at?: Date;
  updated_at?: Date;
  deleted_at?: Date | null;
}
const transactions = {
  tableName: 'transactions',
  columns: ['id', 'amount', 'category', 'transaction_type', 'sender', 'sender_picture', 'date', 'created_at', 'updated_at', 'deleted_at'],
  requiredForInsert: ['amount', 'category', 'transaction_type', 'sender', 'date'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Transactions,
  $input: null as unknown as TransactionsInput
} as const;

// Table users
export interface Users {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
}
export interface UsersInput {
  id?: number;
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  created_at?: Date;
  updated_at?: Date;
  deleted_at?: Date | null;
}
const users = {
  tableName: 'users',
  columns: ['id', 'first_name', 'last_name', 'email', 'password', 'created_at', 'updated_at', 'deleted_at'],
  requiredForInsert: ['first_name', 'last_name', 'email', 'password'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;


export interface TableTypes {
  bills: {
    select: Bills;
    input: BillsInput;
  };
  budgets: {
    select: Budgets;
    input: BudgetsInput;
  };
  pgmigrations: {
    select: Pgmigrations;
    input: PgmigrationsInput;
  };
  pots: {
    select: Pots;
    input: PotsInput;
  };
  transactions: {
    select: Transactions;
    input: TransactionsInput;
  };
  users: {
    select: Users;
    input: UsersInput;
  };
}

export const tables = {
  bills,
  budgets,
  pgmigrations,
  pots,
  transactions,
  users,
}
