/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgres://username:password@database:5432/db123 -t pgmigrations -t users -s public
 *
 */


export type Json = unknown;

// Table pgmigrations
export interface Pgmigrations {
  id: number;
  name: string;
  run_on: Date;
}
export interface PgmigrationsInput {
  id?: number;
  name: string;
  run_on: Date;
}
const pgmigrations = {
  tableName: 'pgmigrations',
  columns: ['id', 'name', 'run_on'],
  requiredForInsert: ['name', 'run_on'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Pgmigrations,
  $input: null as unknown as PgmigrationsInput
} as const;

// Table users
export interface Users {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
}
export interface UsersInput {
  id?: number;
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  created_at?: Date;
  updated_at?: Date;
  deleted_at?: Date | null;
}
const users = {
  tableName: 'users',
  columns: ['id', 'first_name', 'last_name', 'email', 'password', 'created_at', 'updated_at', 'deleted_at'],
  requiredForInsert: ['first_name', 'last_name', 'email', 'password'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;


export interface TableTypes {
  pgmigrations: {
    select: Pgmigrations;
    input: PgmigrationsInput;
  };
  users: {
    select: Users;
    input: UsersInput;
  };
}

export const tables = {
  pgmigrations,
  users,
}
